### ISSUE TITLE
Use with es6 modules and webpack

### ISSUE THREAD

**Issue by dedan** [pkaminski/firebase-on-error#3]
Hello Piotr,

I remembered your name from being a fan of reviewable, when I stumbled upon this package. Also here, thanks for the great work.

This module sounds like exactly what I need, however I have trouble getting it running in my environment. I have a project based on [Create React App](https://github.com/facebookincubator/create-react-app), installed your module via yarn and hoped that a simple `import 'firebase-on-error'` would add the `onError` function to the firebase module that I previously imported via `import Firebase from 'firebase'`.  However that fails with a:

```
Uncaught ReferenceError: Firebase is not defined
    at onerror.js:5
```

Can you maybe point me in the right direction of how to solve that?

Best, Stephan

**Comment by pkaminski** [comment]
Hey Stephan, thanks!  I haven't yet fully taken the leap to ES6 and Webpack so I'm not surprised things are breaking.  My best guess is that the packer doesn't realize that `onerror.js` depends on `firebase.js` because there's no `import` line in `onerror.js`, and hence doesn't load them in the right order.  To check my hypothesis you can try looking for both Firebase and `onerror` in the packed `js` file to see what order they appear in.  If I'm right, I'd try looking for a way to specify the dependency externally -- I assume there must be one, since there are many legacy modules out there.  

BTW, I'm no longer actively maintaining `firebase-on-error`; I've rolled this (and many other features / ideas) into `firetruss`, which is what Reviewable will use going forward.  (It's not at all documented yet, though!)

**Comment by dedan** [comment]
Hey Piotr,

thank you for the hints. Your hypothesis sounds reasonable and I'll try to
find a way to declare Firebase as an external dependency.

Firetruss looks/sounds interesting - I would be happy if you some day find
the time to document it and share it with the world.

Thanks a lot and all the best, Stephan

**Comment by pkaminski** [comment]
Cool, good luck!  I'm going to close this issue as won't fix in case future visitors run into it.

I'll definitely document Firetruss at some point -- I've found it made a night-and-day difference in writing large apps on top of Firebase.  It turns the Firebase tree into a shared, partially-loaded structure that makes it easy to access throughout your code.  It also reduces the impedance mismatch by encouraging you to define custom classes for the Firebase objects, and takes care of computing derived data that's integrated right into the tree, without messing up Firebase writes!  Oh, and also I managed to stick the Firebase code into a shared worker, so it's offloaded to a separate thread and can be shared among multiple tabs.  Plus lots more features that previously required monkey-patching the Firebase SDK...
