### ISSUE TITLE
"firebase-token-generator" is deprecated

### ISSUE THREAD

**Issue by danielberndt** [pkaminski/firebase-on-error#4]
Hi Piotr,
I just stumbled across your code as I was looking for ways to debug failing firebase validation rules.
You recommend to create custom debug auth tokens, but it seems like the [api](https://www.firebase.com/docs/web/guide/login/custom.html) has been deprecated a while ago. Do you still use a method like this for debugging, or did the firebase ecosystem come up with something new that I failed to find?
Thanks a lot :)
Daniel

**Comment by pkaminski** [comment]
Hi Daniel, funny you should ask -- @jwngr has just been working on updating this library for the new Firebase SDK.  The short answer is that no, there's no good new way to debug failing permissions.  The options we've found so far are:

1. Generate a debug auth token and use it with Firebase's REST API, which is still supported and accepts old-style tokens.  The debug info will come back in a `X-Firebase-Auth-Debug` header but unfortunately will be cut off after ~3000 characters, which can be too short depending on the complexity of your rules.

2. Keep using the old SDK for debugging permissions; it's deprecated, but Google hasn't announced any EOL date so it will likely continue to be supported for the foreseeable future.  If you (very reasonably) want to use the new SDK for your app, then you can load the old SDK separately just for the debugging calls.  This will probably only work server-side, since on the client the SDKs' namespaces will collide, but the client could delegate such debugging calls to your server (if you're running one at all).

We're still experimenting to see what works best -- I or @jwngr can follow up here once we've settled on an approach and can confirm it works.

**Comment by danielberndt** [comment]
Ah that's good to know. Thank you so much for your insights! 👍 

Feel free to close, as it seems there's not much that can be done without a lot of effort.

**Comment by pkaminski** [comment]
Yeah, but I think the effort is worth it until Google gets their act together.  Anyway, I'll close this and update the repo README before I archive it.
